# ============================================
# EXTRATIVO.AI - DOCKER COMPOSE (DEVELOPMENT)
# ============================================
# Development configuration with hot reload

version: '3.8'

services:
  # Frontend Application (Development)
  extrativo-frontend-dev:
    image: node:20-alpine
    container_name: extrativo-frontend-dev
    working_dir: /app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    networks:
      - extrativo-network-dev

networks:
  extrativo-network-dev:
    driver: bridge
